included: # paths to include during linting. `--path` is ignored if present.
  - Inbbbox
disabled_rules:
  - LegacyCGGeometryFunctionsRule
# TODO: Refactor code to remove following rules
line_length: 120
function_body_length: 45
variable_name:
  excluded: # excluded via string array
    - mngd_identifier
    - mngd_name
    - mngd_title
    - mngd_username
    - mngd_createdAt
    - mngd_user
    - mngd_team
    - mngd_owner
    - mngd_animated
    - mngd_likesCount
    - mngd_viewsCount
    - mngd_shotsCount
    - mngd_bucketsCount
    - mngd_commentsCount
    - mngd_avatarURL
    - mngd_htmlDescription
    - mngd_accountType
    - mngd_shotImage
    - mngd_hidpiURL
    - mngd_normalURL
    - mngd_teaserURL
file_length:
  warning: 700
  error: 700

